const fs = require('fs'), vm = require('vm'), assert = require('assert/strict'), path = require('path')
const ctx = {}
vm.createContext(ctx)
vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'Model.js'), 'utf8'), ctx)

assert.equal(ctx.volumeReadout(0.72), '72%')
assert.equal(ctx.volumeReadout(0), '0%')
assert.equal(ctx.volumeReadout(1), '100%')
assert.equal(ctx.volumeReadout(null), '—')
assert.equal(ctx.loudness(0, false), 0)
assert.equal(ctx.loudness(0.5, false), 50)
assert.equal(ctx.loudness(1, false), 100)
assert.equal(ctx.loudness(0.2, true), 0)
assert.equal(ctx.barTag(true, 'speaker'), 'MUTE')
assert.equal(ctx.barTag(false, 'headphones'), 'CANS')
assert.equal(ctx.barTag(false, 'bluetooth'), 'BT')
assert.equal(ctx.barTag(false, 'hdmi'), 'HDMI')
assert.equal(ctx.barTag(false, 'speaker'), 'VOL')
assert.equal(ctx.barTag(false, 'none'), 'NONE')
assert.equal(ctx.sinkKind(null), 'none')
assert.equal(ctx.sinkKind({ name: 'headset', description: 'Headphones', ready: true, properties: {} }), 'headphones')
assert.equal(ctx.sinkKind({ name: 'bluez_output.AA', description: 'Bluetooth speaker', ready: true, properties: {} }), 'bluetooth')
assert.equal(ctx.sinkKind({ name: 'hdmi', description: 'HDMI / DisplayPort', ready: true, properties: {} }), 'hdmi')
assert.equal(ctx.sinkKind({ name: 'alsa_output.pci', description: 'Built-in Audio', ready: true, properties: {} }), 'speaker')
assert.equal(ctx.outputVolumeName(0.2, true), 'Muted')
assert.equal(ctx.outputVolumeName(1, false), 'Concert hall')
assert.equal(ctx.outputVolumeName(0.05, false), 'Whisper')
assert.equal(ctx.ramp(0), '#850d29')
assert.equal(ctx.ramp(50), '#efcc45')
assert.equal(ctx.ramp(100), '#43f2a1')
assert.equal(ctx.isPlaybackStream({ isStream: true, isSink: true }), true)
assert.equal(ctx.isPlaybackStream({ isStream: true, isSink: false }), false)
const sinkNode = (name, description, props) => ({ name, description, ready: true, properties: props || {} })
assert.equal(ctx.outputName(null), 'No output')
assert.equal(ctx.outputName(sinkNode('alsa_output.pci-0000_80_1f.3-platform-sof_sdw.HiFi__Speaker__sink', '800 Series Chipset Family Audio Context Engine (ACE) Speaker', { 'device.icon-name': 'audio-speakers' })), 'Laptop Speakers')
assert.equal(ctx.outputName(sinkNode('alsa_output.pci-0000_80_1f.3-platform-sof_sdw.HiFi__Headphones__sink', '800 Series Chipset Family Audio Context Engine (ACE) Headphones')), 'Headphone Jack')
assert.equal(ctx.outputName(sinkNode('alsa_output.pci-0000_80_1f.3-platform-sof_sdw.HiFi__HDMI2__sink', '800 Series Chipset Family Audio Context Engine (ACE) HDMI / DisplayPort 2 Output')), 'HDMI 2')
assert.equal(ctx.outputName(sinkNode('alsa_output.pci-0000_01_00.1.hdmi-stereo', 'GB206 High Definition Audio Controller Digital Stereo (HDMI) [VA2756-UHD]')), 'VA2756-UHD')
assert.equal(ctx.outputName(sinkNode('Sonos Playbar-uuid:RINCON_000000000000001400_MR', 'Office (Sonos Playbar)')), 'Office')
assert.equal(ctx.outputName(sinkNode('Sonos Play:1-uuid:RINCON_000000000000011400_MR', 'Living Room (Sonos Play:1)')), 'Living Room')
assert.equal(ctx.outputName(sinkNode('bluez_output.AC_90_85_00_11_22.1', 'Sam’s AirPods Pro')), 'AirPods Pro')
assert.equal(ctx.outputName(sinkNode('bluez_output.AC_90_85_00_11_23.1', 'AirPods')), 'AirPods')
assert.equal(ctx.outputName(sinkNode('bluez_output.00_11_22_33_44_55.1', 'JBL Flip 5')), 'JBL Flip 5')
assert.equal(ctx.outputName(sinkNode('alsa_output.usb-Focusrite_Scarlett', 'Scarlett 2i2 USB')), 'Scarlett 2i2 USB')
console.log('Audio Pulse output names, readout, loudness, sink kind, mute names and colour ramp pass.')
