const fs = require('fs'), vm = require('vm'), assert = require('assert/strict'), path = require('path')
const ctx = {}
vm.createContext(ctx)
vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'Model.js'), 'utf8'), ctx)

assert.equal(ctx.volumeReadout(0.72), '72%')
assert.equal(ctx.volumeReadout(0), '0%')
assert.equal(ctx.volumeReadout(1), '100%')
assert.equal(ctx.volumeReadout(null), '—')
assert.equal(ctx.loudness(0, false), 0)
assert.equal(ctx.loudness(0.5, false), 50)
assert.equal(ctx.loudness(1, false), 100)
assert.equal(ctx.loudness(0.2, true), 0)
assert.equal(ctx.barTag(true, 'speaker'), 'MUTE')
assert.equal(ctx.barTag(false, 'headphones'), 'CANS')
assert.equal(ctx.barTag(false, 'bluetooth'), 'BT')
assert.equal(ctx.barTag(false, 'hdmi'), 'HDMI')
assert.equal(ctx.barTag(false, 'speaker'), 'VOL')
assert.equal(ctx.barTag(false, 'none'), 'NONE')
assert.equal(ctx.sinkKind(null), 'none')
assert.equal(ctx.sinkKind({ name: 'headset', description: 'Headphones', ready: true, properties: {} }), 'headphones')
assert.equal(ctx.sinkKind({ name: 'bluez_output.AA', description: 'Bluetooth speaker', ready: true, properties: {} }), 'bluetooth')
assert.equal(ctx.sinkKind({ name: 'hdmi', description: 'HDMI / DisplayPort', ready: true, properties: {} }), 'hdmi')
assert.equal(ctx.sinkKind({ name: 'alsa_output.pci', description: 'Built-in Audio', ready: true, properties: {} }), 'speaker')
assert.equal(ctx.outputVolumeName(0.2, true), 'Muted')
assert.equal(ctx.outputVolumeName(1, false), 'Concert hall')
assert.equal(ctx.outputVolumeName(0.05, false), 'Whisper')
assert.equal(ctx.ramp(0), '#850d29')
assert.equal(ctx.ramp(50), '#efcc45')
assert.equal(ctx.ramp(100), '#43f2a1')
assert.equal(ctx.isPlaybackStream({ isStream: true, isSink: true }), true)
assert.equal(ctx.isPlaybackStream({ isStream: true, isSink: false }), false)
console.log('Audio Pulse readout, loudness, sink kind, mute names and colour ramp pass.')
